name: CI on Main branch

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run tests
        run: echo "✅ Main branch workflow has been finished"

      - name: Trigger master workflow
        if: success()
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/main.yml/dispatches \
            -d '{"ref":"master"}'

      - name: Send email notification (Main Branch)
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          smtp-server: smtp.gmail.com  # Use your SMTP server
          smtp-port: 587
          smtp-username: ${{ secrets.EMAIL_USERNAME }}
          smtp-password: ${{ secrets.EMAIL_PASSWORD }}
          from: ${{ secrets.EMAIL_USERNAME }}
          to: mayank07082001@gmail.com # Replace with recipient's email
          subject: "Main Branch Workflow Triggered"
          body: |
           The Main Branch workflow has been successfully completed and the Master Branch workflow has been triggered.
         
