name: CI on Main branch 

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run tests
        run: echo " Main branch workflow has been finished"

      - name: Trigger master workflow
        if: success()
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/main.yml/dispatches \
            -d '{"ref":"master"}'

      - name: Send email notification (Main Branch)
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com  # Use your SMTP server
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}  # Your email username
          password: ${{ secrets.EMAIL_PASSWORD }}  # Your email password
          from: ${{ secrets.EMAIL_USERNAME }}  # Use the same email as sender
          to: mayank07082001@gmail.com  # Replace with recipient's email
          subject: "Main Branch Workflow Triggered"
          body: ${{ secrets.EMAIL_BODY }}
         
