name: CI on Master

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production  

    steps:
      - name: Checkout master
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Send email notification (Approval Pending)
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.action == '' }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          from: ${{ secrets.EMAIL_USERNAME }}
          to: mayank07082001@gmail.com
          subject: "Approval Required for Master Branch Workflow"
          body: |
            Hello,

            The workflow for the **master branch** has been manually triggered.

            

            Best regards,  
            Your CI/CD System

      - name: Run build
        run: echo "🚀 Master branch workflow triggered after approval!"
